title: China 2025
description: Planning for the best trip ever!
theme: just-the-docs

url: https://faerlin-developer.github.io/blog

aux_links:
  Template Repository: https://github.com/faerlin-developer/blog

math: mathjax
